[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .

addopts =
    --cov=task_manager
    # --cov-report=xml:test-results/coverage.xml
    --cov-report=html:test-results/coverage
    --cov-config=.coveragerc
    --junitxml=test-results/TEST.xml
